[mysql]#本地
    user = "scada"
    password = "ScAdA@2019#"
    addr = "192.168.26.10:51016"
    database = "scada"
#[mysql]#浙江
#    user = "scada"
#    password = "ScAdA@2019#"
#    addr = "192.168.26.10:51016"
#    database = "scada"

[kairosdb]
    host = "192.168.26.10"
    port = "51017"
#
#[redis]
#    Addr = "172.201.10.11:16379"
#    Password = "WuTz@DtXyTeCh.com"
#    channels = ["main@scada_calcData"]    # 功率偏差消息通道 当前版本暂未使用该通道
