[database]
    [database.default]
        link = "mysql:scada:scada@tcp(127.0.0.1:3306)/scada"
        charset = "utf8"

[kairosdb]
    host = "192.168.26.10"
    port = 8008

[redis]
    infoBus = "172.201.10.11:16379,0,WuTz@DtXyTeCh.com?maxActive=200&idleTimeout=600s"  #浙江集控redis消息总线配置
    channels = ["main@scada_calcData",     # 功率偏差消息通道 当前版本暂未使用该通道
                "alarm@DTZJJK"]    # 告警通道

[config]
    startDate = "2022-10-01"    # 补算起始日期
    endDate   = "2022-10-20"    #  补算结束日期

[logger]
    Path                 = "./log/"      # 日志文件路径,默认为空，表示关闭，仅输出到终端
    File                 = "{Y-m-d}.log" # 日志文件格式,默认为"{Y-m-d}.log"
    Level                = "INFO"        # DEV(调试模式)、PROD(生产模式)
    StdoutPrint          = true          # 日志是否同时输出到终端,默认true
    RotateSize           = "100M"        # 按照日志文件大小对文件进行滚动切分,默认为0，表示关闭滚动切分特性
    RotateExpire         = 0             # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
    RotateBackupLimit    = 10            # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效,默认为0，表示不备份，切分则删除
    RotateBackupExpire   = "7d"          # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效,默认为0，表示不备份，切分则删除
    RotateBackupCompress = 9             # 滚动切分文件的压缩比（0-9）,默认为0，表示不压缩
    RotateCheckInterval  = "1h"          # 滚动切分的时间检测间隔，一般不需要设置,默认为1小时
[test]
    test = "test"