[mysql]#本地
    user = "scada"
    password = "ScAdA@2019#"
    addr = "192.168.26.10:51016"
    database = "scada"
# [mysql]#宁夏
#    user = "scada"
#    password = "ScAdA@2019#"
#    addr = "172.10.200.13:3306"
#    database = "scada"

[kairosdb]#本地
    host = "192.168.26.10"
    port = "51017"
# [kairosdb]#宁夏
    # host = "172.10.200.13"
    # port = "8008"

[task]
    #历史数据补算
    hiscalcbegintime = "2022-10-04 00:00:00"
    hiscalcendtime = "2022-10-05 00:00:00"
    #历史功率曲线补算
    hiscurvecalctime = "2023-03-01 00:00:00"
    #删除指标
    deldatabegintime = "2023-03-01 00:00:00"
    deldataendtime = "2023-03-07 00:00:00"

[pluspoints]
    [pluspoints.example]
        point = "WNAC_WdSpd"
        aggr = "avg"
        minValue = "0"
        maxValue = "50"
        samplingValue = "10"
        samplingUnit = "minutes"
    [pluspoints.WNAC_WdSpd_MAX_10m]
        point = "WNAC_WdSpd"
        aggr = "max"
        minValue = "0"
        maxValue = "50"
        samplingValue = "10"
        samplingUnit = "minutes"